title: How to type Mandarin
description: ... without wanting to commit sudoku
theme: jekyll-theme-cayman

github:
  is_project_page: false

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false
